services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - pgsql:/var/lib/postgresql/data

  project-svc:
    image: minhkhoitran/project-svc:latest
    build:
      context: .
      dockerfile: src/ProjectService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Postgres=Server=postgres:5432;User Id=postgres;Password=password;Database=projects
    ports:
      - 7001:80
    depends_on:
      - postgres


volumes:
  pgsql: