import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./nav/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='dark:bg-slate-700'>
        <Navbar></Navbar>
        <div className='container mx-auto xl:px-24 pt-10 '>
          {children}
        </div>
      </body>
    </html>
  );
}
